# this file is used to generate a list of projects that
# should be showcases on my website.

# read more here: https://mosaic.luxass.dev
# schema can be found here: https://mosaic.luxass.dev/json-schema.json

[project]
name = "luxass.dev"

[website]
enabled = true
description = "The website you're currently viewing."
