name: Update Projects

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a commit
        required: false
        default: "false"
  schedule:
    # Every night at 1:23
    - cron: "23 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Update Site Script
        run: pnpm run update:site
        env:
          GITHUB_TOKEN: ${{ secrets.LUXASS_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.event.inputs.dry-run != 'true' }}
        with:
          commit_message: "chore: update projects"
          branch: ${{ github.head_ref }}
          file_pattern: "**/projects/*.mdx"
