name: Trigger Vercel Build

on:
  workflow_dispatch:
  schedule:
    # Every night at 1:23
    - cron: "23 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Run Script
        run: pnpx tsx scripts/update-site.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add files
        run: |
          git config user.name luxass
          git config user.email lucasnrgaard@gmail.com
          git add src/data
          git commit -m "chore: updated site data"
          git push
