name: Update Projects

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL'
        default: "https://projectrc.luxass.dev/api/gh/cron-job"
        required: true
  schedule:
    # Every night at 1:23
    - cron: "23 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: update projects
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ github.event.inputs.url }}
          method: 'GET'
          bearerToken: ${{ secrets.PROJECTRC_AUTH_TOKEN }}
