name: update projects

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a pull request
        required: false
        default: "false"
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@v4.1.7

      - name: setup pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: setup node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: run update script
        uses: actions/github-script@v7
        id: update-projects
        with:
          script: |
            const { run } = await import('${{ github.workspace }}/scripts/update-projects.mjs')

            await run({
              github,
              context,
              core,
              glob,
              io,
              exec,
              require,
              __original_require__,
            });

      - name: print output
        run: |
          echo "branchName: ${{ steps.update-projects.outputs.branchName }}"
          echo "created: ${{ steps.update-projects.outputs.created }}"

      - name: create pull request
        if: ${{ github.event.inputs.dry-run }} != 'true' && steps.update-projects.outputs.created == 'true'
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          # token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update projects"
          title: "chore: update projects"
          body: "This PR updates all projects to the latest version."
          branch: ${{ steps.update-projects.outputs.branchName }}
          base: "main"
