name: Update Projects

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Run the workflow without creating a commit
        required: false
        default: "false"
  schedule:
    # Every night at 1:23
    - cron: "23 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ROBOBUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Update Site Script
        run: pnpm run update:site
        env:
          GITHUB_TOKEN: ${{ secrets.LUXASS_TOKEN }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        if: ${{ github.event.inputs.dry-run != 'true' }}
        with:
          commit_message: "fix: use correct list of projects"
          branch: ${{ github.head_ref }}
          commit_user_name: robobub
          commit_user_email: bot@luxass.dev
          file_pattern: "**/projects.ts **/projects/*.md"
